name: MS Teams Deploy Card

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Notify dedicated teams channel
        uses: ./
        with:
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          timezone: Australia/Sydney
          deploy-title: Github Actions CI
